Pimcore\Model\DataObject\AbstractObject:
    attributes:
        id:
            groups: ['read', 'object:read']
            identifier: true
        properties:
            groups: ['read', 'object:read']
        parentId:
            groups: ['read', 'object:read']
        type:
            groups: ['read', 'object:read']
        key:
            groups: ['read', 'object:read']
        path:
            groups: ['read', 'object:read']
        index:
            groups: ['read', 'object:read']
        creationDate:
            groups: ['read', 'object:read']
        modificationDate:
            groups: ['read', 'object:read']
        userOwner:
            groups: ['read', 'object:read']
        userModification:
            groups: ['read', 'object:read']
        dependencies:
            groups: ['read', 'object:read']
        locked:
            groups: ['read', 'object:read']
        versionCount:
            groups: ['read', 'object:read']
