Pimcore\Model\DataObject\AbstractObject:
    attributes:
        id:
            groups: ['get']
            identifier: true
        properties:
            groups: ['get']
        parentId:
            groups: ['get']
        type:
            groups: ['get']
        key:
            groups: ['get']
        path:
            groups: ['get']
        index:
            groups: ['get']
        creationDate:
            groups: ['get']
        modificationDate:
            groups: ['get']
        userOwner:
            groups: ['get']
        userModification:
            groups: ['get']
        dependencies:
            groups: ['get']
        locked:
            groups: ['get']
        versionCount:
            groups: ['get']
