Pimcore\Model\DataObject\Concrete:
    attributes:
        published:
            groups: ['read', 'object:read']
        class:
            groups: ['read', 'object:read']
        classId:
            groups: ['read', 'object:read']
        className:
            groups: ['read', 'object:read']
        versions:
            groups: ['read', 'object:read']
        scheduledTasks:
            groups: ['read', 'object:read']

