Pimcore\Model\Property:
    attributes:
        name:
            groups: ['read', 'object:read']
        data:
            groups: ['read', 'object:read']
        type:
            groups: ['read', 'object:read']
        ctype:
            groups: ['read', 'object:read']
        cpath:
            groups: ['read', 'object:read']
        cid:
            groups: ['read', 'object:read']
        inheritable:
            groups: ['read', 'object:read']
        inherited:
            groups: ['read', 'object:read']

